---
default_install_hook_types:
  - commit-msg
  - pre-push

# Unless otherwise specified, all hooks below are run during pre-commit.
default_stages:
  - pre-commit

repos:
  # Generic hooks that apply to a lot of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

      # The following only check that the files are parseable and does _not_
      # modify the formatting.
      - id: check-toml
      - id: check-xml
