export const QMETRY_DEFAULTS = {
  BASE_URL: "https://testmanagement.qmetry.com",
  PROJECT_KEY: "default",
};

export const QMetryToolsHandlers = {
  FETCH_PROJECTS: "getProjects",
  SET_PROJECT_INFO: "setProjectInfo",
  FETCH_PROJECT_INFO: "getProjectInfo",
  FETCH_RELEASES_CYCLES: "getReleasesCycles",
  FETCH_BUILDS: "getBuilds",
  FETCH_PLATFORMS: "getPlatforms",
  CREATE_TEST_CASE: "createTestCases",
  UPDATE_TEST_CASE: "updateTestCase",
  FETCH_TEST_CASES: "getTestCases",
  FETCH_TEST_CASE_DETAILS: "getTestCaseDetails",
  FETCH_TEST_CASE_VERSION_DETAILS: "getTestCaseVersionDetails",
  FETCH_TEST_CASE_STEPS: "getTestCaseSteps",
  FETCH_TEST_CASE_EXECUTIONS: "getTestCaseExecutions",
  LINK_REQUIREMENT_TO_TESTCASE: "linkRequirementToTestCase",
  FETCH_REQUIREMENTS: "getRequirements",
  FETCH_REQUIREMENT_DETAILS: "getRequirementDetails",
  FETCH_TESTCASES_LINKED_TO_REQUIREMENT: "getTestCasesLinkedToRequirement",
  FETCH_REQUIREMENTS_LINKED_TO_TESTCASE: "getRequirementsLinkedToTestCase",
  CREATE_TEST_SUITE: "createTestSuite",
  UPDATE_TEST_SUITE: "updateTestSuite",
  FETCH_TEST_SUITES: "getTestSuites",
  FETCH_TESTSUITES_FOR_TESTCASE: "getTestSuitesForTestCase",
  FETCH_TESTCASES_BY_TESTSUITE: "getTestCasesByTestSuite",
  FETCH_EXECUTIONS_BY_TESTSUITE: "getExecutionsByTestSuite",
  BULK_UPDATE_EXECUTION_STATUS: "bulkUpdateExecutionStatus",
  FETCH_TESTCASE_RUNS_BY_TESTSUITE_RUN: "getTestCaseRunsByTestSuiteRun",
  FETCH_LINKED_ISSUES_BY_TESTCASE_RUN: "getLinkedIssuesByTestCaseRun",
  FETCH_ISSUES_LINKED_TO_TESTCASE: "getIssuesLinkedToTestCase",
  LINK_TESTCASES_TO_TESTSUITE: "linkTestCasesToTestSuite",
  REQUIREMENTS_LINKED_TESTCASES_TO_TESTSUITE: "reqLinkedTestCasesToTestSuite",
  CREATE_ISSUE: "createIssue",
  UPDATE_ISSUE: "updateIssue",
  FETCH_ISSUES: "getIssues",
  LINK_ISSUES_TO_TESTCASE_RUN: "linkIssuesToTestcaseRun",
  LINK_PLATFORMS_TO_TESTSUITE: "linkPlatformsToTestSuite",
  IMPORT_AUTOMATION_RESULTS: "importAutomationResults",
  FETCH_AUTOMATION_STATUS: "fetchAutomationStatus",
};
