export const QMETRY_PATHS = {
  PROJECT: {
    GET_PROJECTS: "/rest/admin/project/list",
    GET_INFO: "/rest/admin/project/getinfo",
    GET_RELEASES_CYCLES: "/rest/admin/scope/tree",
    GET_BUILD: "/rest/admin/drop/list",
    GET_PLATFORMS: "/rest/admin/platform/list",
  },
  TESTCASE: {
    GET_TC_LIST: "/rest/testcases/list/viewColumns",
    GET_TC_DETAILS: "/rest/testcases/getVersionDetail",
    GET_TC_DETAILS_BY_VERSION: "/rest/testcases/list",
    GET_TC_STEPS: "/rest/testcases/steps/list",
    GET_TC_EXECUTIONS: "/rest/testcases/execution",
    GET_TC_LINKED_TO_RQ: "/rest/testcases/list/forRQ",
    CREATE_UPDATE_TC: "/rest/testcases",
    LINKED_RQ_TO_TC: "/rest/testcases/link/requirements",
  },
  REQUIREMENT: {
    GET_RQ_LIST: "/rest/requirements/list/viewColumns",
    GET_RQ_DETAILS: "/rest/requirements/detail/data",
    GET_RQ_LINKED_TO_TC: "/rest/requirements/list/forTC",
  },
  TESTSUITE: {
    CREATE_UPDATE_TS: "/rest/testsuites",
    GET_TS_LIST_FOR_TC: "/rest/testsuites/list/forTC",
    GET_TS_LIST: "/rest/testsuites/list/viewColumns",
    GET_TESTCASES_BY_TESTSUITE: "/rest/testcases/list/forTS",
    LINKED_TESTCASES_TO_TESTSUITE: "/rest/testsuites/dolink/TCs",
    GET_EXECUTIONS_BY_TESTSUITE: "/rest/execution/list/platformHome",
    GET_TESTCASE_RUNS_BY_TESTSUITE_RUN: "/rest/execution/list/viewColumns",
    GET_LINKED_ISSUES_BY_TESTCASE_RUN: "/rest/execution/issue/list/forTCRun",
    LINK_PLATFORMS_TO_TESTSUITE: "/rest/testsuites/link/platforms",
    BULK_UPDATE_EXECUTION_STATUS: "/rest/execution/runstatus/bulkupdate",
  },
  ISSUES: {
    GET_ISSUES_LIST: "/rest/issues/list/viewColumns",
    CREATE_UPDATE_ISSUE: "/rest/issues",
    GET_ISSUES_LINKED_TO_TC: "/rest/issues/list/ForTC",
    LINK_ISSUES_TO_TESTCASE_RUN: "/rest/execution/link/issue",
  },
  AUTOMATION: {
    IMPORT_RESULTS: "/rest/import/createandscheduletestresults/1",
  },
};
