import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import { Node, Project, SyntaxKind } from "ts-morph";

const API_FILE_PATH = "src/bugsnag/client/api/api.ts";

const HEADER_COMMENT = `/** biome-ignore-all lint/complexity/useLiteralKeys: auto-generated code */
/** biome-ignore-all lint/correctness/noUnusedVariables: auto-generated code */
/** biome-ignore-all lint/complexity/useOptionalChain: auto-generated code */
/** biome-ignore-all lint/style/useLiteralEnumMembers: auto-generated code */
/** biome-ignore-all lint/suspicious/noEmptyInterface: auto-generated code */
// tslint:disable
/**
 * BugSnag - Data Access API
 *
 * The following code is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * To update:
 *   1. Run \`npm run update:bugsnag\` to automatically download and prune unused code
 *   2. Check \`git diff\` to ensure the changes are correct
 */

import * as url from "node:url";
import type { Configuration } from "./configuration";
`;

async function downloadAndExtractApi() {
  console.log("Fetching Swagger spec from SmartBear...");
  const specResponse = await fetch(
    "https://api.swaggerhub.com/apis/smartbear-public/bugsnag-data-access-api/2/swagger.json",
  );
  if (!specResponse.ok) {
    throw new Error(`Failed to fetch spec: ${specResponse.statusText}`);
  }
  const specJson = await specResponse.json();

  console.log(
    "Requesting TypeScript client generation from Swagger Generator...",
  );
  const genResponse = await fetch(
    "https://generator.swagger.io/api/gen/clients/typescript-fetch",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        options: { modelPropertyNaming: "original" },
        spec: specJson,
      }),
    },
  );

  if (!genResponse.ok) {
    throw new Error(`Failed to generate client: ${genResponse.statusText}`);
  }

  const { link } = await genResponse.json();
  if (!link) {
    throw new Error("No download link returned from generator.");
  }

  console.log(`Downloading generated client from ${link}...`);
  const zipPath = "/tmp/bugsnag-client.zip";
  execSync(`curl -s "${link}" -o ${zipPath}`);

  console.log("Extracting api.ts...");
  const extractedApi = execSync(
    `unzip -p ${zipPath} typescript-fetch-client/api.ts`,
  ).toString("utf-8");

  console.log("Preparing new api.ts content...");

  // Find where the actual code starts (after the generated header and imports)
  // Typically it starts with `export const BASE_PATH` or `export interface`
  let rawCode = extractedApi.replace(
    /\/\/\/ <reference path="\.\/custom\.d\.ts" \/>\n/,
    "",
  );
  // Remove the generated header comment
  rawCode = rawCode.replace(/\/\*\*[\s\S]*?\*\//, "").trim();
  // Remove duplicate original imports, as we inject our own with node:url and type imports
  rawCode = rawCode.replace(/import \* as url from "url";\n/, "");
  rawCode = rawCode.replace(
    /import { Configuration } from "\.\/configuration";\n/,
    "",
  );
  rawCode = rawCode.replace(/\/\/ tslint:disable\n/, "");

  fs.writeFileSync(API_FILE_PATH, HEADER_COMMENT + "\n" + rawCode.trimStart());
  console.log(`Saved newly extracted base code to ${API_FILE_PATH}`);
}

async function main() {
  await downloadAndExtractApi();

  console.log(`Loading project and analyzing ${API_FILE_PATH}...`);
  const project = new Project({
    tsConfigFilePath: "tsconfig.json",
  });

  // Force a reload from disk since we just modified it
  const sourceFile = project.getSourceFileOrThrow(API_FILE_PATH);
  await sourceFile.refreshFromFileSystem();

  console.log("Removing portable-fetch and isomorphic-fetch imports if any...");
  for (const moduleName of ["isomorphic-fetch", "portable-fetch"]) {
    const fetchImport = sourceFile.getImportDeclaration(
      (decl) => decl.getModuleSpecifierValue() === moduleName,
    );
    if (fetchImport) {
      fetchImport.remove();
    }
  }

  console.log(
    "Removing Fp and Factory constants, and object-oriented API classes...",
  );

  const varsToRemove = [];
  for (const varDecl of sourceFile.getVariableDeclarations()) {
    const name = varDecl.getName();
    if (name.endsWith("ApiFp") || name.endsWith("ApiFactory")) {
      varsToRemove.push(varDecl);
    }
    // Also remove unused Scim and Integrations creators
    if (
      name === "ScimApiFetchParamCreator" ||
      name === "IntegrationsApiFetchParamCreator"
    ) {
      varsToRemove.push(varDecl);
    }
  }

  for (const v of varsToRemove) {
    v.getVariableStatement()?.remove();
  }

  const classesToRemove = [];
  for (const classDecl of sourceFile.getClasses()) {
    const name = classDecl.getName() || "";
    if (name.endsWith("Api")) {
      classesToRemove.push(classDecl);
    }
  }
  for (const c of classesToRemove) {
    c.remove();
  }

  console.log(
    "Removing BaseAPI, FetchAPI, BASE_PATH, and COLLECTION_FORMATS...",
  );
  sourceFile.getInterface("FetchAPI")?.remove();
  sourceFile.getClass("BaseAPI")?.remove();
  sourceFile.getVariableStatement("BASE_PATH")?.remove();
  sourceFile.getVariableStatement("COLLECTION_FORMATS")?.remove();

  console.log("Stripping unreferenced exports using ts-morph...");
  const exportedDeclarations = sourceFile.getExportedDeclarations();
  let strippedCount = 0;

  for (const [name, declarations] of exportedDeclarations) {
    for (const decl of declarations) {
      if ("setIsExported" in decl && typeof decl.setIsExported === "function") {
        const referencedNodes = decl.findReferencesAsNodes();
        const isUsedOutside = referencedNodes.some(
          (n) => n.getSourceFile().getFilePath() !== sourceFile.getFilePath(),
        );

        if (!isUsedOutside) {
          (decl as any).setIsExported(false);
          strippedCount++;
        }
      }
    }
  }

  console.log(`Stripped ${strippedCount} unused exports.`);

  console.log("Saving changes...");
  await project.save();

  console.log("Formatting the file with biome...");
  try {
    execSync(`npx biome check --write --unsafe ${API_FILE_PATH}`, {
      stdio: "inherit",
    });
  } catch (err) {
    console.error("Warning: biome format failed.", err);
  }

  console.log("Running pre-commit hooks on the generated file...");
  try {
    execSync(`prek run --files ${API_FILE_PATH}`, { stdio: "inherit" });
  } catch (err) {
    console.error("Warning: pre-commit hooks failed.", err);
  }

  console.log("BugSnag API update automation completed.");
}

main().catch(console.error);
