name: Publish to npm

permissions:
  contents: read

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Update server.json version
        run: |
          jq --arg v "${{ steps.extract_version.outputs.VERSION }}" \
            '.version = $v | .packages[0].version = $v' \
            server.json > server.json.tmp && mv server.json.tmp server.json
      - name: Check server.json
        run: cat server.json