name: Publish to npm

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Update server.json version
        run: |
          jq --arg v "${{ steps.extract_version.outputs.VERSION }}" \
            '.version = $v | .packages[0].version = $v' \
            server.json > server.json.tmp && mv server.json.tmp server.json

      - name: prepare mcp-publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.2.3/mcp-publisher_1.2.3_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher
      
      - name: Login
        run: |
          ./mcp-publisher login github-oidc
          ./mcp-publisher login dns --domain smartbear.com --private-key "${{ secrets.GH_MCP_REGISTRY_KEY }}"
      
      - name: Publish to MCP Registry
        run: ./mcp-publisher publish