name: Publish to ECR

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to publish'
        required: true

jobs:
  publish-ecr:
    name: Publish to ECR Registry
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: ${{ secrets.ECR_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR public
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # 2.0.1
        with:
          registry-type: public
      
      - name: Login to Amazon ECR private
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076

      - name: Build, tag, and push docker image to Amazon ECR Public    
        env:
          ECR_PUBLIC_ALIAS: r2q3q1g5
          REPOSITORY: smartbear-mcp
          IMAGE_TAG: 0.5.0
        run: |
          PUBLIC_IMAGE="public.ecr.aws/${ECR_PUBLIC_ALIAS}/${REPOSITORY}:${IMAGE_TAG}"
          PRIVATE_IMAGE=${{ secrets.ECR_PRIVATE_REGISTRY_URL }}/${REPOSITORY}:${IMAGE_TAG}
          
          docker build -t "$PUBLIC_IMAGE" -t "$PRIVATE_IMAGE" .
          
          docker push "$PUBLIC_IMAGE"
          
          docker push "$PRIVATE_IMAGE"