name: Publish to npm

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - uses: actions/setup-go@v6.0.0
        with:
          go-version: '1.25'

      - name: Build mcp-publisher
        run: |
          git clone https://github.com/modelcontextprotocol/registry
          cd registry
          make publisher
          ls -la bin/
          cp bin/mcp-publisher "$GITHUB_WORKSPACE"/mcp-publisher

      - name: Login
        run: |
          ./mcp-publisher login github-oidc
          ./mcp-publisher login dns --domain smartbear.com --private-key "${{ secrets.GH_MCP_REGISTRY_KEY }}"
      
      - name: Publish to MCP Registry
        run: ./mcp-publisher publish