name: Test Suite

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]
  workflow_dispatch:

permissions:
  contents: read

env:
  # Generic
  FORCE_COLOR: '1'
  CLICOLOR: '1'
  # Node
  STABLE_NODE_VERSION: '22'

jobs:
  # This job checks if the necessary checks have been completed and is used by
  # GitHub's rules to determine if the PR can be merged. This more convenient
  # than specifying each individual check in the GitHub UI.
  complete:
    name: Test completion check
    if: always()

    permissions:
      contents: none

    runs-on: ubuntu-latest
    needs:
      - build
      - coverage
      - format
      - lint
      - prek
      - test

    steps:
      - name: Failed
        run: exit 1
        if: >
          contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled')
          || contains(needs.*.result, 'skipped')

  build:
    name: Build on Node.js ${{ matrix.node-version }} / ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, windows-latest, macos-latest, windows-11-arm, ubuntu-22.04-arm]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  coverage:
    name: Code coverage

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js ${{ env.STABLE_NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.STABLE_NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage
        run: npm run test:coverage

      - name: Generate badge
        run: ./scripts/generate-badge

      - name: Upload coverage reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report
          path: |
            coverage/
            !coverage/**/*.tmp
          retention-days: 30

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const { default: postCoverageComment } = await import('${{ github.workspace }}/scripts/post-coverage-comment.js');
            await postCoverageComment({
              github,
              context,
            });

  format:
    name: Code format check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.STABLE_NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code format
        run: npm run format:check

  lint:
    name: Code lint check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.STABLE_NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code lint
        run: npm run lint

  prek:
    name: Prek (pre-commit)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8    # v5.0.0

      - name: Cache prek
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809    # v4.2.4
        with:
          path: |-
            ~/.cache/prek
          key: >-
            ${{ runner.os }}-prek-${{
              hashFiles(
                '**/.pre-commit-config.yaml',
                '**/.pre-commit-config.yml'
              ) }}
          restore-keys: |-
            ${{ runner.os }}-prek-

      - name: Set up uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6    # v6.6.1
        with:
          enable-cache: true
          cache-suffix: prek
          cache-dependency-glob: |-
            **/.pre-commit-config.yaml
            **/.pre-commit-config.yml

      - name: Install prek
        run: uv tool install prek

      - name: Run prek
        run: prek run --show-diff-on-failure --color=always --all-files

  test:
    name: Test on Node.js ${{ matrix.node-version }} / ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, windows-latest, macos-latest, windows-11-arm, ubuntu-22.04-arm]


    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run
